// ── compile subcommand: connect to MCP server → extract schemas → generate SKILL.md ──
import { writeFileSync } from 'node:fs';
import { MCPClient } from '@mcp-html-bridge/mcp-client';
import { renderFromSchema } from '@mcp-html-bridge/ui-engine';
import type { JSONSchema } from '@mcp-html-bridge/ui-engine';

export async function compile(serverCommand: string, outputPath: string): Promise<void> {
  const client = new MCPClient();

  console.log(`  Connecting to: ${serverCommand}`);
  await client.connect({ command: serverCommand });

  console.log('  Listing tools...');
  const tools = await client.listTools();
  console.log(`  Found ${tools.length} tools`);

  const sections: string[] = [];

  sections.push('# MCP Tool UI Reference\n');
  sections.push(`> Auto-generated by mcp-html-bridge from \`${serverCommand}\``);
  sections.push(`> ${tools.length} tools discovered\n`);

  for (const tool of tools) {
    console.log(`  Processing: ${tool.name}`);

    const schema = tool.inputSchema as JSONSchema;
    const html = renderFromSchema(schema, {
      toolName: tool.name,
      toolDescription: tool.description,
    });

    sections.push(`## ${tool.name}\n`);
    if (tool.description) {
      sections.push(`${tool.description}\n`);
    }
    sections.push('```mcp-html');
    sections.push(html);
    sections.push('```\n');
  }

  const content = sections.join('\n');
  writeFileSync(outputPath, content);
  console.log(`\n  ✓ Written to ${outputPath}`);

  await client.disconnect();
}
